[project]
name = "fair-charging-station-data"
version = "0.1.0"
description = "FAIR BNEtzA data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "frictionless>=5.18.1",
    "jsonschema-rs>=0.30.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
